services:
  web:
    image: node:24
    working_dir: /mins_menu
    volumes:
      - .:/mins_menu
      - node_modules:/mins_mune/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "8002:8002"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://menu:menu@db:5432/menu?schema=public"

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: menu
      POSTGRES_PASSWORD: menu
      POSTGRES_DB: menu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
  node_modules: